{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.adamko.vcsmvnpub",
    "module": "vcs-mvn-publish",
    "version": "main-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vcs-mvn-publish-main-SNAPSHOT.jar",
          "url": "vcs-mvn-publish-main-SNAPSHOT.jar",
          "size": 120805,
          "sha512": "e720fb202948af7238b3202ff664b3869a3126e20f7fafda54651b1f6c35454d4206163ea5396462d72f4ab8d1ceaf1e1c028bc422f515035a5970bed64c923d",
          "sha256": "0bc9bef66c732acb39fd9890696ab3f1351384d72e0b9b57d149e7d43679e943",
          "sha1": "5f5b0ec5b4ff5856ef6f34cbe956d51bd6004a37",
          "md5": "cfd220f5867c13e7cf012040dc3211f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0-RC2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-util-io",
          "version": {
            "requires": "1.8.0-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "vcs-mvn-publish-main-SNAPSHOT.jar",
          "url": "vcs-mvn-publish-main-SNAPSHOT.jar",
          "size": 120805,
          "sha512": "e720fb202948af7238b3202ff664b3869a3126e20f7fafda54651b1f6c35454d4206163ea5396462d72f4ab8d1ceaf1e1c028bc422f515035a5970bed64c923d",
          "sha256": "0bc9bef66c732acb39fd9890696ab3f1351384d72e0b9b57d149e7d43679e943",
          "sha1": "5f5b0ec5b4ff5856ef6f34cbe956d51bd6004a37",
          "md5": "cfd220f5867c13e7cf012040dc3211f2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vcs-mvn-publish-main-SNAPSHOT-javadoc.jar",
          "url": "vcs-mvn-publish-main-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vcs-mvn-publish-main-SNAPSHOT-sources.jar",
          "url": "vcs-mvn-publish-main-SNAPSHOT-sources.jar",
          "size": 15984,
          "sha512": "027a78a69ffc1046602e191685fc7dc96ac8b194c027e4b3995ac0c6ba9081acbe8f8bd3f32f1f4f2697c749f7a6c8c61b61661da635ae01c706a3ab2fa842d7",
          "sha256": "9b0f4be22c172d319df5420b9b12427072de0265a32b1ffa68ca4db4997c8d35",
          "sha1": "2994bed398b75fb240e3c5e5452f92391dc85282",
          "md5": "8d98f43ddb02ea18301a0335fd663f96"
        }
      ]
    }
  ]
}
