name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:

  publish:
    uses: ./.github/workflows/gradle_task.yml
    with:
      runs-on: ubuntu-latest
      gradle-task: check gitRepoPublish --stacktrace
